apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      containers:
        - name: flask
          image: expense-flask:v2
          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          # Restart container if Flask becomes unhealthy
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          # Don't send traffic until Flask is ready
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          env:
            - name: MYSQL_DB_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DB_URL